name: Deploy Docker image

on:
  push:
    tags: 
      - "*"
    paths:
      - "./dockerfile"
      - "./.github/workflows/deploy.yml"
      - "./start.sh"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - name: Docker hub login
        id: docker-hub-login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - uses: docker/build-push-action@v5
        name: Build and push image
        id: build-and-push-image
        with:
          file: ./dockerfile
          push: true
          tags: ${{secrets.DOCKER_IMAGE_TAG}}:${{github.ref_name}}

