name: Hadolint

on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        name: Installing and executing hadolint
        with:
          dockerfile: dockerfile
      
