name: trivy

on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/nicolascbv/${{secrets.DOCKER_IMAGE_TAG}}:${{ github.sha }} .
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/nicolascbv/${{secrets.DOCKER_IMAGE_TAG}}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
